micronaut:
  application:
    name: carros
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/carros_grpc?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update